# CI workflow that publishes pull requests merged into main to production

name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: sync
        env:
          dest: 'klimafaelden.dk@linux374.unoeuro.com:/var/www/klimafaelden.dk/public_html/'
        run: |
          echo "${{secrets.DEPLOY_SSH_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /.gitignore \
            --exclude /README.md \
            ./ ${{env.dest}}
